In [1]:
# importing numpy library
import numpy as np

Compute an inversion of a matrix

In [4]:
# let matrix be A
A = np.array([[1,0.2,0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
A

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

In [6]:
# computing the inversion of a matrix
A_transpose=A.T
print(f'Inversion of matrix A is: {A_transpose}')

Inversion of matrix A is: [[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


Compute the determinant of the matrix

In [9]:
# computing the determinant of the matrix
A_det = np.linalg.det(A)
print(f'{A_det} is the determinant of the matrix')

0.2299999999999999 is the determinant of the matrix


Decomposing the matrix

In [10]:
# Matrix decomposition of matrix A
from scipy.linalg import lu

In [12]:
# performing an LU decomposition
A = np.array([[1,0.2,0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
L,U = lu(A, True)
print(f'L is {L} and U is {U}')

L is [[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]] and U is [[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]


In [13]:
# perfoming a QR decomposition
from scipy.linalg import qr

In [14]:
A = np.array([[1,0.2,0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
Q,R= qr(A, True)
print(f'Q is {Q} and R is {R}')

Q is [[-0.88045091  0.38615039 -0.27512557]
 [-0.17609018 -0.80507368 -0.566435  ]
 [-0.44022545 -0.4502713   0.77682515]] and R is [[-1.13578167 -0.70436073 -1.02132305]
 [ 0.         -1.08806065 -0.90125505]
 [ 0.          0.          0.18611436]]


d. matrix transformation

In [19]:
import numpy as np
import scipy
A = np.array([[1,0.2,0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
# rotating a matrix at an angle of 90 degrees
rotation_degrees = 90
rotation_radians = np.radians(rotation_degrees)
# transforming the matrix on the x, y and z axis
rotation_axis = np.array([0, 0, 1])

rotation_matrix = rotation_radians * rotation_axis
rotation = scipy.spatial.transform.Rotation.from_rotvec(rotation_matrix)
rotated_matrix = rotation.apply(A)
 
print(f'The transformation matrix of A is:{rotated_vector}')

The transformation matrix of A is:[[-0.2  1.   0.5]
 [-1.   0.2  0.8]
 [-0.8  0.5  1. ]]
